name: 'CICD'
on:
  push:
    branches:
      - $default-branch
jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master

      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.13.x

      - run: terraform fmt
      - run: terraform init

      - name: 'Inject provider configs for validate command'
        run: |
            cat > providers.tf <<EOF
            provider "aws" {
              region = "us-east-2"
            }
            EOF
      - run: terraform validate

  release:
   if: github.event_name == 'push'
   needs: terraform
   runs-on: ubuntu-latest

   steps:
   - uses: actions/checkout@v2
   - name: Semantic Release
     id: semantic
     uses: cycjimmy/semantic-release-action@v2
     env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
     with:
       semantic_version: 17
       extra_plugins: |
         @semantic-release/changelog
         @semantic-release/git